<?xml version="1.0" encoding="utf-8"?><Database Name="TerraZonDB" Class="DCterrazonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=TerraZonDB;Integrated Security=True" SettingsObjectName="TerraHomes.Properties.Settings" SettingsPropertyName="TerraZonDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Property" Member="Properties" ThisKey="UserID" OtherKey="OwnerID" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.AgentsProperties" Member="AgentsProperties">
    <Type Name="AgentsProperty">
      <Column Name="AgentPropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgentID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Property_AgentsProperty" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyImages" Member="PropertyImages">
    <Type Name="PropertyImage">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Property_PropertyImage" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Properties" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(550)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Property_AgentsProperty" Member="AgentsProperties" ThisKey="PropertyID" OtherKey="PropertyID" Type="AgentsProperty" />
      <Association Name="Property_PropertyImage" Member="PropertyImages" ThisKey="PropertyID" OtherKey="PropertyID" Type="PropertyImage" />
      <Association Name="User_Property" Member="User" ThisKey="OwnerID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetData" Method="sp_GetData">
    <ElementType Name="sp_GetDataResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertSignUp" Method="sp_InsertSignUp">
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>