<?xml version="1.0" encoding="utf-8"?><Database Name="TerraZonDB" Class="DCterrazonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=TerraZonDB;Integrated Security=True" SettingsObjectName="TerraHomes.Properties.Settings" SettingsPropertyName="TerraZonDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AgentsProperties" Member="AgentsProperties">
    <Type Name="AgentsProperty">
      <Column Name="AgentPropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Property_AgentsProperty" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
      <Association Name="User_AgentsProperty" Member="User" ThisKey="AgentID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyImages" Member="PropertyImages">
    <Type Name="PropertyImage">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Property_PropertyImage" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Properties" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(550)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Property_AgentsProperty" Member="AgentsProperties" ThisKey="PropertyID" OtherKey="PropertyID" Type="AgentsProperty" />
      <Association Name="Property_PropertyImage" Member="PropertyImages" ThisKey="PropertyID" OtherKey="PropertyID" Type="PropertyImage" />
      <Association Name="Property_Transaction" Member="Transactions" ThisKey="PropertyID" OtherKey="PropertyID" Type="Transaction" />
      <Association Name="User_Property" Member="User" ThisKey="OwnerID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Property_Transaction" Member="Property" ThisKey="PropertyID" OtherKey="PropertyID" Type="Property" IsForeignKey="true" />
      <Association Name="Customer_Transaction" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="User_Transaction" Member="User" ThisKey="AgentID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="Customer_Transaction" Member="Transactions" ThisKey="CustomerID" OtherKey="CustomerID" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="imageURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="User_AgentsProperty" Member="AgentsProperties" ThisKey="UserID" OtherKey="AgentID" Type="AgentsProperty" />
      <Association Name="User_Property" Member="Properties" ThisKey="UserID" OtherKey="OwnerID" Type="Property" />
      <Association Name="User_Transaction" Member="Transactions" ThisKey="UserID" OtherKey="AgentID" Type="Transaction" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetData" Method="sp_GetData">
    <ElementType Name="sp_GetDataResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertSignUp" Method="sp_InsertSignUp">
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteAgentsProperties" Method="sp_DeleteAgentsProperties">
    <Parameter Name="agentpropID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteUsers" Method="sp_DeleteUsers">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteCustomers" Method="sp_DeleteCustomers">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteProperties" Method="sp_DeleteProperties">
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeletePropertyImages" Method="sp_DeletePropertyImages">
    <Parameter Name="imageID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteTransactions" Method="sp_DeleteTransactions">
    <Parameter Name="transactionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetAgentProperties" Method="sp_GetAgentProperties">
    <ElementType Name="sp_GetAgentPropertiesResult">
      <Column Name="AgentPropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetCustomers" Method="sp_GetCustomers">
    <ElementType Name="sp_GetCustomersResult">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetProperties" Method="sp_GetProperties">
    <ElementType Name="sp_GetPropertiesResult">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(550)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetPropertyImages" Method="sp_GetPropertyImages">
    <ElementType Name="sp_GetPropertyImagesResult">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTransactions" Method="sp_GetTransactions">
    <ElementType Name="sp_GetTransactionsResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertAgentProperties" Method="sp_InsertAgentProperties">
    <Parameter Name="agentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertCustomers" Method="sp_InsertCustomers">
    <Parameter Name="fname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertProperties" Method="sp_InsertProperties">
    <Parameter Name="propname" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(550)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="price" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="size" Type="System.String" DbType="VarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertTransactions" Method="sp_InsertTransactions">
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="agentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateAgentProperties" Method="sp_UpdateAgentProperties">
    <Parameter Name="agentpropID" Type="System.Int32" DbType="Int" />
    <Parameter Name="agentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateCustomers" Method="sp_UpdateCustomers">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="fname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdatePropertyImages" Method="sp_UpdatePropertyImages">
    <Parameter Name="imageID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="imageURL" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateTransactions" Method="sp_UpdateTransactions">
    <Parameter Name="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="agentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertPropertyImages" Method="sp_InsertPropertyImages">
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="imageURL" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertUsers" Method="sp_InsertUsers">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="usertype" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="imageURL" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateProperties" Method="sp_UpdateProperties">
    <Parameter Name="propertyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="propname" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(550)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="price" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="size" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="ownerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateUsers" Method="sp_UpdateUsers">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="usertype" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="imageURL" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetUsers" Method="sp_GetUsers">
    <ElementType Name="sp_GetUsersResult1">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="imageURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetAllUsers" Method="sp_GetAllUsers">
    <ElementType Name="sp_GetAllUsersResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="imageURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeleteAllPropertyImages" Method="sp_DeleteAllPropertyImages">
    <Parameter Name="propID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>